//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDF.TotalAgility.Connector.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        "PPDF.TotalAgility.Connector.Resources.Resources",
                        typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // ── Bitmaps ───────────────────────────────────────────────────────────

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        ///   Used in TAResultForm error state and Menu fallback.
        /// </summary>
        internal static System.Drawing.Bitmap Alert_triangle {
            get {
                object obj = ResourceManager.GetObject("Alert_triangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        ///   Ribbon button icon — 100% DPI.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Open {
            get {
                object obj = ResourceManager.GetObject("Image_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        ///   Ribbon button icon — 150% DPI.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Open_150 {
            get {
                object obj = ResourceManager.GetObject("Image_Open_150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        ///   Ribbon button icon — 200% DPI.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Open_200 {
            get {
                object obj = ResourceManager.GetObject("Image_Open_200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        ///   Ribbon button small icon — 100% DPI.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Open_Small {
            get {
                object obj = ResourceManager.GetObject("Image_Open_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        ///   Ribbon button small icon — 150% DPI.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Open_Small_150 {
            get {
                object obj = ResourceManager.GetObject("Image_Open_Small_150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        ///   Ribbon button small icon — 200% DPI.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Open_Small_200 {
            get {
                object obj = ResourceManager.GetObject("Image_Open_Small_200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        ///   Loading animation shown in LoadingForm while submitting to TotalAgility.
        ///   Note: stored as Bitmap — use a GIF if animation is required.
        /// </summary>
        internal static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        ///   Used in TAResultForm success state.
        /// </summary>
        internal static System.Drawing.Bitmap Success_icon {
            get {
                object obj = ResourceManager.GetObject("Success_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        ///   Used in TAResultForm error state (warning variant).
        /// </summary>
        internal static System.Drawing.Bitmap Warning_Alert {
            get {
                object obj = ResourceManager.GetObject("Warning_Alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        ///   Ribbon button save icon — 100% DPI. Used as loading form icon.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Save {
            get {
                object obj = ResourceManager.GetObject("Image_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Save_150 {
            get {
                object obj = ResourceManager.GetObject("Image_Save_150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Save_200 {
            get {
                object obj = ResourceManager.GetObject("Image_Save_200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Save_Small {
            get {
                object obj = ResourceManager.GetObject("Image_Save_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Save_Small_150 {
            get {
                object obj = ResourceManager.GetObject("Image_Save_Small_150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Save_Small_200 {
            get {
                object obj = ResourceManager.GetObject("Image_Save_Small_200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        // ── Strings ───────────────────────────────────────────────────────────

        /// <summary>
        ///   Looks up a localized string: "Send to TotalAgility".
        ///   Used as the ribbon button label in Menu.cs.
        /// </summary>
        internal static string MenuSendToTotalAgility {
            get {
                return ResourceManager.GetString("MenuSendToTotalAgility", resourceCulture);
            }
        }
    }
}
