//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDF.TotalAgility.Connector.Resources
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPDF.TotalAgility.Connector.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static System.Drawing.Bitmap Alert_triangle
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Alert_triangle", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_Open
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_Open", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_Open_150
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_Open_150", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_Open_200
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_Open_200", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_Open_Small
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_Open_Small", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_Open_Small_150
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_Open_Small_150", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_Open_Small_200
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_Open_Small_200", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_Save
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_Save", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_Save_150
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_Save_150", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_Save_200
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_Save_200", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_Save_Small
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_Save_Small", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_Save_Small_150
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_Save_Small_150", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_Save_Small_200
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_Save_Small_200", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_TA
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_TA", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_TA_150
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_TA_150", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_TA_200
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_TA_200", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_TA_Small
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_TA_Small", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_TA_Small_150
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_TA_Small_150", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_TA_Small_200
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_TA_Small_200", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_TA_Configure
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_TA_Configure", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_TA_Configure_150
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_TA_Configure_150", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_TA_Configure_200
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_TA_Configure_200", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_TA_Configure_Small
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_TA_Configure_Small", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_TA_Configure_Small_150
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_TA_Configure_Small_150", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Image_TA_Configure_Small_200
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Image_TA_Configure_Small_200", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Success_icon
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Success_icon", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Warning_Alert
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Warning_Alert", resourceCulture); }
        }

        internal static System.Drawing.Bitmap Loading
        {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Loading", resourceCulture); }
        }

        internal static string MenuConfigureTotalAgility
        {
            get { return ResourceManager.GetString("MenuConfigureTotalAgility", resourceCulture); }
        }

        internal static string MenuSendToTotalAgility
        {
            get { return ResourceManager.GetString("MenuSendToTotalAgility", resourceCulture); }
        }
    }
}